[theme]
# primary accent color for interactive elements
primaryColor = "#d33682"

# background color for the main content area
backgroundColor = "#002b36"

# background color for the sidebar and most interactive widgets
secondaryBackgroundColor = "#586e75"

# Color used for almost all text.
textColor = "#fff"

[client]
toolbarModel = "minimal"

[database]
query_01 = """
select 
    OCM01IDNOA  , OCM01NAMEA    ,                  /* 환자번호, 이름름 */
    OCM01SYSDAT , OCM01SYSTM                       /* 날짜, 시간 */                              /* 이미지파일명 */
from OCMPTN01
"""
query_02 = """
select
    OCM02RGCD   , OCM02RGNM     ,                  /* 수술지구분 */
    OCM02HPDAT  , OCM02RTDAT    ,                  /* 환자번호, 타급종구분 */
    OCM02SYSDAT , OCM02SYSTM                       /* 내원 및 입원일, 수술일, 순서 */
from OCMDCT02
"""

query_12 = """
select 
    OCM06STATUS	,                                  /* 수술지구분 */
    OCM06IDNOA	, OCM06IDNOB    ,                  /* 환자번호, 타급종구분 */
    OCM06LWDAT	, OCM06OPDAT    , OCM06SEQNO    ,  /* 내원 및 입원일, 수술일, 순서 */
    OCM06IOCD   , OCM06DV       ,                  /* IO구분, 구분, */
    OCM06CMTA	, OCM06CMTB     , OCM06CMTC   	,  /* 마취방법, 수술기록1, 수술기록2 */
    OCM06RGCD   , OCM06SYSTM    , OCM06SYSDAT	,  /* 등록의, 등록시간, 등록일 */
    OCM06IMGFILE10                                 /* 이미지파일명 */
from OCMOPR06
"""

query_15 = """
select 
    OCM32STATUS ,                                  /* STATUS */
    OCM32IDNOA  , OCM32IDNOB    , OCM32LWDAT    ,  /* 환자번호, 타급종구분, 래원 및 입원 */
    OCM32IOCD   , OCM32BHCD     ,                  /* I/O구분, 급종 */
    OCM32HPDAT  , OCM32RTDAT    ,                  /* 입원일, 퇴원일 */
    OCM32KWA    , OCM32WARD	    ,                  /* 성별, BEDNO */
    OCM32CHIEFCOMP, OCM32FINALDX, OCM32OP       ,  /* CHIEF COMPLAINTS, FINAL DX, TREATMENT OP */
    OCM32MEDICAL, OCM32FOLLOW	, OCM32OTHER    ,  /* TREATMENT MEDICAL, FOLLOW-UP PLAN, OTHER REMARKS */
    OCM32SPTH   , OCM32SEX      , OCM32AGE	    ,  /* 주치의(진료과장), 성별, 나이 */
    OCM32RTRSTCD, OCM32RTTYPECD , OCM32RTHSPNM	,  /* 치료결과코드, 퇴원형태코드, 전원병원명 */
    OCM32RTCMT  , OCM32SCNDDX   ,                  /* 기타CMT, 부진단명 */
    OCM32PI     , OCM32PHX      , OCM32DM       ,
    OCM32TBC    , OCM32HT       , OCM32AST      ,
    OCM32SYSDAT , OCM32SYSTM    ,                  /* 등록날짜. 등록시간, 담당의(레지턴트,가정) */
    OCM32RGCD   , OCM32RTRSTTXT , OCM32PROBLEM     /* 담당의(레지던트,진료과장), 중요검사소견 */
from OCMRTN32
"""
